name: Build and Deploy Infrastructure to Azure

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_USE_OIDC: "true"

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    if: ${{ success() }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform -chdir=./infrastructure init

      - name: Terraform Validate
        run: terraform -chdir=./infrastructure validate

      - name: Terraform Plan
        run: terraform -chdir=./infrastructure plan -out=plan.tfplan -var="${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./infrastructure/plan.tfplan
  
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: ./infrastructure

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init (Reinitialize)
        run: terraform -chdir=./infrastructure init

      - name: Terraform Apply
        run: terraform -chdir=./infrastructure apply -auto-approve plan.tfplan
